---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-key
  namespace: helium
spec:
  encryptedData:
    secret: AgANerYIRGzhIJVbNohwoWXLHUpoDGqoiIlBPLOL3WCoFAjSHrydzRzNwfux6g4WR6wk9cAyqgFUUnyAGIhAvgviTxrndgaIXbhlcL7G9eaO5TLH+xEyXuR1JLz0Cqx/AtemSGVABKaLSH2DRw4+Im8PL3Bb6tGO+zWXE/sk9tJMLGXLq947Sg8kW8h04xuJbK9N70yVDiLbvq+Z/bwDZKEP1UeOAOJRe/cRe8pcS3sDMVUVlkMQ5d1D2e+32DkOAPMzNgg9tgadBX2UdeFeKAfiMQ9Tml15aL9vX5Bh4dqfHiY/Zey26nBaDdOlD7OSbvpyHDLXVuon873kBXa9vKBZiwrgmOwTMPJe8DcshpBL4VsI0m9+puLsxCcHlUA+IJGknOC77F7fJ2HCZaxlMg4czCgo9/IxO5IB+4FnBY9KMAOv7YhAqHBpOmtf5MMZa2/AXE1uC7TolhYghps8lPYxhamexOt+a4MhmlvWYejErGR2gotQvq0cX7OYVb6qrpTtZzKdY81X0vUBB2BCOfbLQx4XxoDZ0vksRUWZFgyhuYVPWNXpU9fh0EAOTvu1zH9aiM/q9TvyN/z2HdMUA4p6oMLoLa0FQHsgQ8mFCflJIctIt2rvOPtZl4SIMbwxCLWbKnontG4hWuTNEAbMwrjE8ofQTF+cfdcQhmwrYxV3i9RVprqsVu6C2kGu5ijeu602BxfeQ+eP3aHlznh/XAZNWqflhw==
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-key
      namespace: helium
