---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-keys
  namespace: ingress-nginx
spec:
  encryptedData:
    unlimited-rate-api-keys.conf: AgByoYhT3XWNUy4tQGKXo5rsN9pHwe0mnr+8rHSo6xqUlCOM7YJUOFlE31Fl9V5rS3hHWlQINzZoPWA1BNetXO4awxo+WyhoTMQskQyTJM9dE0a8jcjJvkB/BtLDPcxP5ZIbS8MqNs/8EkQiYRipkxvB27VoghOxL7uiPWS4S03RKh8wY8FDhdJGh/Lnv7+BW03szKbEBl4YOIQyRxY7TC/VfYNk3h9jKw6n3ktAxqUszMixbP2e63CtigJUF5EvBhALDegDHAncaGW+wHxNgE5dxpx5vltw2ZLmsyr2NA4S1zwuQyvYsWS5byf23FtY4hOk0HbRMj7LAb6+QbAQ80cu5YS8xqKGqOeCUXrf4Agy67net8FGyVGOEEW3ltI9HubecnTMxaB2x4gstpE3m+bcyJg+/gRCg3ooKOaqDqnlptIIv6Erqml6la7hp7HAsMLmfAVyoZ10VszxMebsDLKOm+P4YghevNzI9r+xpJCmhQI61gwHptnSmrqi+7RgjQPM8Bl3FtATXEvzQhPbFvDQFU/6Bi4DwRajtPUBUx9AeAcLw9p1kQIVAtHhOEQ3jOPuBz6gsJ3VWFm/5x+HLuGGF+D9+giTjed7GC+knUYICLxhHqM16uQBi3o+aYggD6TpoUKUreaNUAaUmyhZIDH2l/lBFntJHYmgVEF54aeDQo0bN02v34COcW1jLbM4TkPOHWRbAxdhSiW2pn4qyfh/yyEwOcrUBJPo6i0=
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-keys
      namespace: ingress-nginx
