apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-keys
  namespace: ingress-nginx
spec:
  encryptedData:
    unlimited-rate-api-keys.conf: AgCnnhAerqgAwTYBjtcbD+0FNAHjBBLHMOBvSocqRdec0wD6uyfg89rww373rtliJ99yXF3GvIoHIReSxRqhAeedLKdNEFqUhr6Zp6uGG8rYvFBpEbWTLNO2o1UpfL9zCF7YUbRlCu7Cjg9D0yuTJM6mJmK/LhQC5cXSJKfFybu9cT7YWkAILC4PWrWggl1+bpuEbWPRiahxuGzPfswERqyi1PGIUQaZ3zF/jVWNP6DGo+01ewZKkPxBxicaFmYh4D4wAfm/m6Lmxwy5cajyE5ARZSowFUe+XAe03UB7rfG7KqF+tGuFWEmjjhj7Wyt3a+G0LmNRa2PMkbimtxI1bqQLn9rZ8xNP/lZ2P2WT0+mHabQxoExtzY9OeZEqe45/+r/HMMu1AIWkCd1ToAoRDKSy3IAkBHRgFw5ImJGIP8ludWqPDfuXfJB6HRS9YvzDYXjU1qlLHyYK8GGZvEXxNoQCzIA6n7IiXV9Vc13WdyCBz4o5hyeJCINwdYqbW5YKEjfQEGD6JkQiVav0eVupuhd0bsSY+J+O3qiCU/Sz+xe6vvq0fVp8lXZ0tZMgxcnoBCwe7XoHeiQ5wG+ypy7Xa6I9Kw2S4o8se1Fr/6nSkMtuX+h7j9zOgWlsqOEgbAlRXCaWxobFOv20rfd2lF+JWp1yIJhsSnaN4xmUjyRwqNUwO1Cv9r3doTL2Mj+pX3UA11VwAuNak9ajmbqu79MjZtZAo2XF56wgmmTJma8=
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-keys
      namespace: ingress-nginx

