---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: substream-api-key
  namespace: helium
spec:
  encryptedData:
    secret: AgC3gDw0ZeiTrrYG1QOMAtWX0Lg6OKQ5SCQwPRvcL8czHXjDbi3Oof8oFmiUB27BFZhuuOXU8iiPaFAgqQUnvO3JtNuZQUp6JFnEaCrjWZdawHn/asX5PsFPOiEUal7XvWAEpJm1BK4Ws82xT14jDCEc/8XuaaLnRKA9Hx4F3D028vxkzrGqG7nv3y2o4ZiJdkndLUHywFk3DQE6oQQ0869biJXYF2Hg5MZ/SdSImMHECpYK+pL4vyVKMS48j2Kp0pGjA+Oz0Eqdg3Tny74gLhwTGkQKm6ulIRYFCaF/XqnMlFIAGh5uykFIQRv2joovAedW4wW8lzZA7AI+rdO4dSULYxSbOGtyKqm1roxbGzvrU6Gb4AkAlWFtdhVKG+r5C4VHGoer2srSNJwu9wTSQ4+RzR5fn/uYG5hX8Urd2hM1CZDr6rXQcyLm1UlOzxlY2AtEBbrDP/o+ErjMuke1T4IR1ZNm6R/H3/xTL+14VuWVArSUy/l1mWVsZwXPgFSuv8lxjvnRmPq1lqYU+rsrAvpf3jovSNgv+LKA/vt0BFlXLZL1Q7bpley3YOEu72fLA2FoF9ghRpLvKbWs6qiOv4zfXY7CWACWT492Z400QitDghriNiC2OBCVAZD/Lvx79MKxi1A9PIvMFxNDMpU1WDmBNVMlLI3+qU/y++HVvBnjWyhdsC8il24NpC3xXc11TOevy3Nsu4xAvUC0dt+nIs8m75vMbRZPeuqL/JEt3Av/etw/tvcz8By3
  template:
    metadata:
      creationTimestamp: null
      name: substream-api-key
      namespace: helium
