---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: substream-api-key
  namespace: helium
spec:
  encryptedData:
    secret: AgA8YqjekuQitguel9IqOvqppDDF7Cqo3+upNuO7NvLC/dxhhZe/NVHWhmZXr+yCy3N/7mrpdsFMxMwCrXwe/0BjpEzuF7FG6jotUUw4uE6SZxy9TXwHpPzV1R77mpIMkz+bbhlwjbAu53hA8GkK3d8I2hRpkWGKLk0sApcor7UgrpnJJbVLapkymeqmCpsKwfWMkuYRPsdkcQeYsdix2iPpzCoT+6iQBL2Qhv1jD6gVfKKXSLDPf5REwkZIkiFJds6Yz+AOrsNtSdKixAlDuR2s5UNifLjY2bH/8PHo5l9Z6doZHfvDFDv2bx7jLzfdwXfTCe4qCb98jwEWQXyfvdB+tlCPTA5mY9gXk1UOjrpZLBCn/gtc78ljm2rm+ivDJP5bcokbQAFc7KwKmnMWh43pI4PnBCZQQucaizSnAp7+pnuqqxz4Dpis/Y7PUtILHze2hQ4yyhkRJ0ZtaNZAGW/9OtOPL0U5zWvWXgRYBepKIFDXTH8k5YNat9VcYMl3BarUEaQuhNLerWcsj0MiVuENr4UAUDGL9VbnmmvWVNqY8J5PT20gZqsVVzYPbZeOXnLk0SvkPnuLuWMDfHodgVLkhZskTJaxWLuZRXvEf0d4A3EWrbKGn7IJKjjaclnSFnLEzHUmKo0/wkOY6V0u9lYaQLt3bnNsmW6Fk36seb+q1l4YfFv6+GA83gd5Q0hjeLs/9o7njCNxJ0MCk0GctmabdzjBRP29uQCTORqxMUMHWX4C1LWhUs+p
  template:
    metadata:
      creationTimestamp: null
      name: substream-api-key
      namespace: helium
