---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-key
  namespace: helium
spec:
  encryptedData:
    secret: AgBSKbFRVGRAnDIRBQA4TCFS6XEd/PmNKFxoYjMMGylE+umiHk1h4uwPGubxgS6m2RCOKN1LIlfz7z1mhNb0GAJeBajBb0kvgtOmWYfqDVuLd3M8Aa0x7MHoOonTII4U1zmQb2ETlucWgtECX/kfDzQ67LuGTcd/jcKUPvn4eT+FyZXz7wTTxzXr8vqWvwpIR8Yr6NtvYf7BqnY8ZlgjxLfaTgH+pKy0oKybjXqT1U/Oxp2KT6GQLFd/Xz6xOlu0qWJh+Y0msuK7vjfD4PSfDYVSX2fU3xffMYYQTtM1EsqEDGOQ2UQo7GkZMO6ccLLL1zxB0i4sm0+5/L4RqG6TgNuXz7eCbVOS34QoKr5nDZV3a0JGC3SWbofu6YNJmNFDAwPqNjM0qDQO9Vu+ZeMoM9406dxvy8LRmRINfqaD2xT5YteMNlSKNSMc3cyZGYVbkRdvPRQ0P8dc96JRjsiXodIOVO+Hq4aV6T/3YR5UtL5yxLn+8x9NyfYLOiT5GNzXMEvdz+62uyhFjMi2HVq0+limdBqeyGX/HJDxtDRvblNEgLZ8TJDlwJGlo7x26V7n6LgyiZViPE+/BIHd9S0YDa8Zg+dq2Ca9T2iM53MqthMcypwNgev4NBAoNpoFTWnm5COW5uZ25jkt2C8aSP1FUDoofDdbmWElSdoQOyRUIv82AwKbyF66zYfMhse+cHoIpo15XOpX/mecPQ==
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-key
      namespace: helium
