---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-keys
  namespace: ingress-nginx
spec:
  encryptedData:
    unlimited-rate-api-keys.conf: AgAqn4raU5fJpdWE+Nw7AtcaISIs78koXnYqhxwaz+hzR3LUy7scmZ11bKpc1mh7sD4MQ0XMIFgKAYIvr2dTrvtpT/YnDSu2Yz06kJddmxeM9WILDsMjTaB5j9+0QuW3Vt4/ZopPhj4amU+XehCe9O2JqR2EIlXewbl3k+i7Y+N4SGAlxF+aIIw4YgEMdqN/5oG3Lrt95k2BBU9nMtAbz0AWraZNF/cT5fzKNVWlWwz85nQ3oY0rGrvqAM+0pYUvxywwpKle3eTwB0L5FwDIC57IdqD/u1SUQFR5ChhsxPgWwnmqAx2bzt2LEdJisx6F9JcU4KT3b0NyzcohZLXUAcJcvowLC77+1+kpDid0jAf8DT5cJOUj9NiAzLeWYPSU3HR9MLxpXnuFUngqboivRjPUuD7ZtNyMiUsezXiOefnvvCYNzR04weWbz+P5fibHyJL+1eeqxXQiqSEztuN3zKJkRdk0fMO0CKFZMWGGr/kLIcLKZFjD0SZB9GOqbrUvuUBzppFWgujjeK64Hy+zRGoKBMSOfUM+pMh7Gu+hiAwgz9B9aMLpudSFB32RWnopz1SwB2M+TraFXHLO2zZwTxUD0VJoiNMqsMeD4l0Ar8ojiVPjcZmfNruO5PTYrgGMnqVSRV2VianrUIbpSZ+2vgCLvExacB//HOjUpXBuk2ytkPF55YKiKapJNJyWuM3kI6Hwscn2+Ndt+HmzuN7StFk=
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-keys
      namespace: ingress-nginx