apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-keys
  namespace: ingress-nginx
spec:
  encryptedData:
    unlimited-rate-api-keys.conf: AgAcql1hgXExFYVNle2PwGWEfeGptYCzdd8zNjNqV6Fe/l9PIjUZ1mO5KVKjnUSpBr+IM7pSH0niUj+6yYr+xNIGN/5Rb/sZBDgvBrpTQQjSLc9oCsnw0Z+T3Kw3eBJK96C9+OuRtppRBmLkgkEqa8eI1PTobbuQ2hoEG5/mUF+masZsZzWHQMypEo97h1WarCPuQzBpTObaMbxl4soRbIhWZCv7phCQsZt35lSQUK67eaC+H+8zK3pm2lvhEhieb0fk6CdUNzhrX/997mcjJX5qKSpkg7nN085tS/mfhhAAZ8Q9N2C0Udvxp7zKme0IQVRU1NWnF8PoCKxNlYpKT/vPDJQqSXEFJ5hXYIVVu4zkK3XVJgJHoJvAnU3+9sg7hrisNAx8It9Eu5U4XhS+Az/V43aggKmW3LEFGD2GQU9pAEevh79bcRz4EGd/nMYgfOUajjyn7nSOo6huv7NKTPuesB/U4oLusiYhsl00O0gvJ4AhgoT7R6AYkihggrhQ2UexsvD75DvNZRoH7Qu/accslCvyr4Wp0qbO+9JWs/ndTnykyWkYeSQrHAAsizH27vfEUYYjtLYaGRohB2FqpIM5gaJFepzOveFmg6jv15tBAx4B2xaozO4bd8MVbct317k3KIlkA1cDzsom32dtMQK1WetwNrG70ivFq9yMjpMPuM+9HzLUf62I7wwSK3NgilmG7Rod/R648Q3tNKbwO9w=
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-keys
      namespace: ingress-nginx