apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unlimited-rate-api-keys
  namespace: ingress-nginx
spec:
  encryptedData:
    unlimited-rate-api-keys.conf: AgBDnGHnCTo0Z0UbjS+5B87PnTfR+twNrwprjbFR7fcWVbG1XZR3He5xlF4u0FYubuaUKeAIu0dxjdeUdfDa+QPKySU4fPD7tHpa2uuwlbbOM3rzIKjoFhQ978AH1NtQr/0bE97JcvVneIAee5n38G8DFnrZwKAWW7fiMIFBI+ZRIaDVI0aXFCsCPECQ3wuRYjDVsieffyljkfTXSevmM1lYbVRlmHhp86IALCFKGiVaLghS/WHUBrWQTNId+OOAfCLRZk4u4T0MT9aVMzKMlplahrtS/F60Dy/L9E0sOwV1p/XCQR0SYx8x26+IUnnHnl1pCeWu7hUhBpauxgjrMZWWUZldCAgZpYN4YplMwF44a0W5MPhTr9C5ywel5KGV4MaBJIiGgTGq6yfkYkzuZXz0Oian/nhgea/n1M6yP3IBOg2En2i7L8Ek4TP4BctTvzWEnRKtMGACnb0rCXrlUt1WZJLRxWpFHDBF8sz4GbDYCX4xMdJ+zGUYBPjxSYcsymBfqn4IuxOsBWh37vFN4IC6lAM6ysQI1DobDWZqu8C388xGmjgFFJAdebsaSZJajh95BRGXrUVCxzm0Wyakk4rVDvp+aDS78hlPWP/37ZHB+VvFEuIY7/GLJofRgA5WB6P5bbT9sIDQdXbhwb4S8o4sP45rzmvCJGrxfEuMBHFnyxumO+gSoyEjSYTmXZEeBbL3qQrloE9/+a8QJMklird2
  template:
    metadata:
      creationTimestamp: null
      name: unlimited-rate-api-keys
      namespace: ingress-nginx